airship-in-a-pod: set libvirt tty=false
This sets the airship-in-a-pod libvirt container to have `tty: false`.
With `tty: true`, the libvirt container would fail with the following
error in some environments (mostly baremetal, but VMs as well):

Error: failed to create containerd task: failed to create shim:
OCI runtime create failed: container_linux.go:380: starting container
process caused: process_linux.go:545: container init caused:
setctty: operation not permitted: unknown

The RC for the error is unknown, but `tty: true` appears to be a leftover
debugging tool, so this change disables it by default.

Change-Id: I427bd1bdbe86c8a742b871c4f8fc18e4be58660b
Closes: #578